package game;

public class Square {
  // TO BEDZIE KLASA NADRZEDNA DO BISQUARE I SMALLSQUARE (BIGSQUARE I SMALL SQUARE BEDA DZIEDZICZYC Z TEJ KLASY)
  // LUB INTERFEJS ALBO OBA
  // TRZEBA METODE CHECKWIN DAC DO KLASY NADRZEDNEJ A JAKIES INNE FUNCKJE DODAC DO INTERFEJSU
}
